import { getMockupSystemPrompt } from "@/lib/json-render/catalog"
import { sanitizeInput } from "./sanitize"

export function buildMockupPrompt(mvpPlan: string, projectName: string): string {
  const fence = "```"
  const safeName = sanitizeInput(projectName, 200)
  const safePlan = sanitizeInput(mvpPlan, 50000)
  const catalogPrompt = getMockupSystemPrompt(safeName)

  return [
    catalogPrompt,
    "",
    "---",
    "",
    `**Product Name:** <user_input name="projectName">${safeName}</user_input>`,
    "**MVP Plan:**",
    `<user_input name="mvpPlan">${safePlan}</user_input>`,
    "",
    "## Your Task",
    "",
    "Create WIREFRAME mockups for the key pages from the MVP plan above.",
    "Wireframes focus on LAYOUT and STRUCTURE — not detailed content.",
    "Generate one json-render spec per page/screen.",
    "",
    "## Required Pages",
    "",
    "1. **Homepage** — full-width hero area, feature grid, pricing section, CTA",
    "2. **Key Feature Pages** — main app screens from the MVP plan with realistic layouts",
    "3. **Dashboard** — main logged-in view with stats grid, data table, sidebar (if applicable)",
    "",
    "## Wireframe Design Principles",
    "",
    "CRITICAL: Your wireframes must look like REAL app layouts — not a narrow list of components stacked vertically.",
    "",
    "### Layout Rules",
    "- Every major section (nav, hero, features, footer) must SPAN THE FULL WIDTH of the page",
    "- Use Grid (columns=2 or columns=3) to arrange Cards SIDE BY SIDE — never stack narrow cards vertically when they can go in a grid",
    "- Dashboard pages: use Grid with columns=3 or columns=4 for stat cards, then Grid columns=2 for main content + sidebar",
    "- Navigation: horizontal Stack with logo left, links center, buttons right — spanning full width",
    "- Hero sections: full-width Card containing heading, description, and CTA buttons",
    "- Feature sections: Grid with columns=3 containing feature Cards side by side",
    "- Forms: wrap in a full-width Card, use Grid columns=2 for side-by-side input fields",
    "",
    "### Content Rules",
    "- Use SHORT labels only (1-3 words): 'Sign Up', 'Search', 'Dashboard', 'Save'",
    "- Headings should be brief page/section titles: 'Hero Section', 'Features', 'Pricing'",
    "- Text elements describe WHAT goes there: 'Tagline text', 'Feature description', 'User bio'",
    "- Use Skeleton for images/banners/media placeholders",
    "- Keep forms minimal: input fields with short placeholder labels",
    "- Tables: 3-4 columns with short headers, inside full-width Cards",
    "- Aim for 15-30 elements per page — enough for a realistic layout",
    "- Create 3-5 pages total",
    "",
    "## CRITICAL OUTPUT FORMAT",
    "",
    "Your response MUST follow this exact structure — markdown headers followed by JSON code blocks.",
    "Study this example carefully — note how Grid creates multi-column layouts and Cards fill the width:",
    "",
    "### Homepage",
    "",
    `${fence}json`,
    '{',
    '  "root": "root",',
    '  "elements": {',
    '    "root": {',
    '      "type": "Stack",',
    '      "props": { "direction": "vertical", "gap": "lg" },',
    '      "children": ["nav", "hero", "features-section", "cta-section"]',
    '    },',
    '    "nav": {',
    '      "type": "Stack",',
    '      "props": { "direction": "horizontal", "gap": "md", "align": "center", "justify": "between" },',
    '      "children": ["logo", "nav-links", "nav-actions"]',
    '    },',
    '    "logo": {',
    '      "type": "Heading",',
    '      "props": { "text": "AppName", "level": "h3" },',
    '      "children": []',
    '    },',
    '    "nav-links": {',
    '      "type": "Stack",',
    '      "props": { "direction": "horizontal", "gap": "sm" },',
    '      "children": ["link-features", "link-pricing", "link-about"]',
    '    },',
    '    "link-features": { "type": "Button", "props": { "label": "Features", "variant": "ghost" }, "children": [] },',
    '    "link-pricing": { "type": "Button", "props": { "label": "Pricing", "variant": "ghost" }, "children": [] },',
    '    "link-about": { "type": "Button", "props": { "label": "About", "variant": "ghost" }, "children": [] },',
    '    "nav-actions": {',
    '      "type": "Stack",',
    '      "props": { "direction": "horizontal", "gap": "sm" },',
    '      "children": ["btn-login", "btn-signup"]',
    '    },',
    '    "btn-login": { "type": "Button", "props": { "label": "Log In", "variant": "outline" }, "children": [] },',
    '    "btn-signup": { "type": "Button", "props": { "label": "Sign Up" }, "children": [] },',
    '    "hero": {',
    '      "type": "Card",',
    '      "props": { "title": "Hero Section" },',
    '      "children": ["hero-banner", "hero-text", "hero-buttons"]',
    '    },',
    '    "hero-banner": { "type": "Skeleton", "props": { "height": "200px" }, "children": [] },',
    '    "hero-text": { "type": "Text", "props": { "text": "Tagline and value proposition" }, "children": [] },',
    '    "hero-buttons": {',
    '      "type": "Stack",',
    '      "props": { "direction": "horizontal", "gap": "sm" },',
    '      "children": ["hero-cta", "hero-secondary"]',
    '    },',
    '    "hero-cta": { "type": "Button", "props": { "label": "Get Started" }, "children": [] },',
    '    "hero-secondary": { "type": "Button", "props": { "label": "Learn More", "variant": "outline" }, "children": [] },',
    '    "features-section": {',
    '      "type": "Stack",',
    '      "props": { "direction": "vertical", "gap": "md" },',
    '      "children": ["features-heading", "features-grid"]',
    '    },',
    '    "features-heading": { "type": "Heading", "props": { "text": "Features", "level": "h2" }, "children": [] },',
    '    "features-grid": {',
    '      "type": "Grid",',
    '      "props": { "columns": 3, "gap": "md" },',
    '      "children": ["feat-1", "feat-2", "feat-3"]',
    '    },',
    '    "feat-1": {',
    '      "type": "Card",',
    '      "props": { "title": "Feature One" },',
    '      "children": ["feat-1-desc"]',
    '    },',
    '    "feat-1-desc": { "type": "Text", "props": { "text": "Feature description" }, "children": [] },',
    '    "feat-2": {',
    '      "type": "Card",',
    '      "props": { "title": "Feature Two" },',
    '      "children": ["feat-2-desc"]',
    '    },',
    '    "feat-2-desc": { "type": "Text", "props": { "text": "Feature description" }, "children": [] },',
    '    "feat-3": {',
    '      "type": "Card",',
    '      "props": { "title": "Feature Three" },',
    '      "children": ["feat-3-desc"]',
    '    },',
    '    "feat-3-desc": { "type": "Text", "props": { "text": "Feature description" }, "children": [] },',
    '    "cta-section": {',
    '      "type": "Card",',
    '      "props": { "title": "Ready to start?" },',
    '      "children": ["cta-text", "cta-btn"]',
    '    },',
    '    "cta-text": { "type": "Text", "props": { "text": "Call to action message" }, "children": [] },',
    '    "cta-btn": { "type": "Button", "props": { "label": "Get Started" }, "children": [] }',
    '  }',
    '}',
    fence,
    "",
    "## Rules",
    "",
    "- IMPORTANT: Do NOT use JSON Patch format ({\"op\":\"add\",\"path\":...}) — output complete JSON objects only",
    "- Each JSON block must be a COMPLETE, self-contained json-render spec with `root` and `elements` at the top level",
    "- Every element must have `type`, `props`, and `children` (even if children is empty [])",
    "- Use short descriptive IDs (e.g., 'nav', 'hero', 'sidebar', 'form-section')",
    "- WIREFRAME RULE: Keep ALL text short — labels (1-3 words), descriptions (3-6 words max)",
    "- Use Skeleton for image/media placeholders instead of Image components",
    "- Only use component types from the catalog above",
    "- Use Stack (direction='vertical') as the root element for each page",
    "- LAYOUT RULE: Use Grid (columns=2 or columns=3) to arrange Cards side by side — NEVER stack all Cards vertically",
    "- LAYOUT RULE: Nav bars must use horizontal Stack with justify='between' to span full width",
    "- LAYOUT RULE: Dashboard pages need Grid layouts for stats and content areas — not a vertical list",
    "- Do NOT use advanced features like $state, $bindState, $template, visible conditions, or repeat — keep specs static",
    "- Keep each page spec focused: 15-30 elements for realistic layouts",
  ].join("\n")
}
